from flask import Flask, jsonify

app = Flask(__name__)


@app.route("/health")
def health():
    return jsonify({
        "service": "flask-api",
        "status": "healthy"
    })


@app.route("/reports")
def reports():
    return jsonify({
        "service": "flask-api",
        "message": "Machine report generated by Flask"
    })


if __name__ == "__main__":
    app.run(
        host="0.0.0.0",
        port=5000
    )